/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolb;

import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

/**
 *
 * @author Esteban Olaya
 */
public class GUI extends javax.swing.JFrame {

    Lista datos;
    Raiz raiz1;

    private mxGraph mGraph;
    public int WinWidth = 700;
    public int WinHeight = 600;
    public int LROffset = 135;
    public int DownOffset = 50;
    public int nodeD = 26;
    public int levelOffset = 50;    
    private int ordenArbol = 1;
    boolean ya = false;
    boolean existe = false;
    Raiz raizAux = new Raiz(2);

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        frameArbol = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        bInsetar = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        bEliminar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bIniciarArbol = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bVerArbol = new javax.swing.JButton();

        frameArbol.setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel4.setText("El Arbol B de orden 1 con los valores ingresados es el siguiente: ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout frameArbolLayout = new javax.swing.GroupLayout(frameArbol.getContentPane());
        frameArbol.getContentPane().setLayout(frameArbolLayout);
        frameArbolLayout.setHorizontalGroup(
                frameArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frameArbolLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4)
                                .addContainerGap(115, Short.MAX_VALUE))
                        .addGroup(frameArbolLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        frameArbolLayout.setVerticalGroup(
                frameArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frameArbolLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setToolTipText("Numero entero");

        bInsetar.setText("Insertar");
        bInsetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setToolTipText("Numero entero");
        jTextField3.setPreferredSize(new java.awt.Dimension(73, 20));

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setToolTipText("Numero entero");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bInsetar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(jTextField1))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(jTextField2))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bEliminar)
                                        .addComponent(bInsetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19))
        );

        //Botón inicializar árbol B
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear"));
        bIniciarArbol.setText("Iniciar");
        bIniciarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(bIniciarArbol)))
                                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bIniciarArbol)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualizar"));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 92));

        bVerArbol.setText("Ver Arbol");
        bVerArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bVerArbol)
                                .addGap(96, 96, 96))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(bVerArbol)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }

    /*ActionPerformed del botón buscar, el cual busca la clave dentro del árbol
    e informa si se encuentra o no.*/
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {

        if (!jTextField2.getText().equals("")) {
            boolean numero = raizAux.esNumero(jTextField2.getText());
            if (numero) {
                if (ya) {
                    boolean esta = raiz1.buscar(Integer.parseInt(jTextField2.getText()));
                    if (esta) {
                        JOptionPane.showMessageDialog(this, "El elemento "
                                + jTextField2.getText() + " SI se encuentra en el arbol B",
                                "Dato encontrado!!!", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "El elemento "
                                + jTextField2.getText() + " NO se encuentra en el arbol B",
                                "Dato no encontrado!!!", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Aun no ha creado un arbol",
                            "Error!!", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese numeros entero diferentes de 0",
                        "Error!!", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese datos en el campo",
                    "Error!!", JOptionPane.WARNING_MESSAGE);
        }
        jTextField2.setText("");
    }
    
    /*ActionPerformed del botón ver arbol, el cual muestra el framArbol e imprime
    toda la información del arbol. */
    private void bVerArbolActionPerformed(ActionEvent evt) {
        raiz1.arbol = "";
        if (ya) {
            //Se imprime la Raiz del árbol
            String raiz = "raiz [ ";
            for (int i = 0; i < raiz1.primerNodo.valores.length && raiz1.primerNodo.valores[i] != 0; i++) {
                raiz += raiz1.primerNodo.valores[i] + ", ";
            }
            raiz += " ]\n";
            
            //Se recorre el resto del árbol
            raiz += raiz1.llamarRecorrer();
            
            //Se envía la información del árbol por medio de un TextArea
            jTextArea1.setText(raiz);
        }
        frameArbol.setVisible(true);
    }

    //ActionPerformed del botón iniciar arbol, el cual inicia un árbol B grado 1.
    private void bIniciarArbolActionPerformed(java.awt.event.ActionEvent evt) {
        raiz1.arbol = "";
        datos = new Lista();
        existe = true;
        raiz1 = new Raiz(ordenArbol);
        ya = true;
        JOptionPane.showMessageDialog(this, "Se creo un nuevo árbol B de orden "
                + ordenArbol,
                "Actualización", JOptionPane.WARNING_MESSAGE);
    }

    /*ActionPerformed del botón insertar, el cual inserta la clave dentro del árbol
    e informa si ya se encuentra o no.*/
    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {

        if (!jTextField1.getText().equals("")) {
            boolean numero = raizAux.esNumero(jTextField1.getText());
            if (numero) {
                boolean adentro = false;
                if (existe) {
                    for (int i = 0; i < datos.ingresados.size(); i++) {
                        if (datos.ingresados.get(i) == Integer.parseInt(jTextField1.getText())) {
                            adentro = true;
                        }
                    }
                }
                if (!adentro) {
                    if (!jTextField1.getText().equals("")) {
                        if (!jTextField1.getText().equals("0")) {
                            if (ya) {
                                raiz1.insertar(Integer.parseInt(jTextField1.getText()));
                                JOptionPane.showMessageDialog(this, "El elemento "
                                        + jTextField1.getText() + " fue ingresado al arbol B exitosamente",
                                        "Novedad", JOptionPane.WARNING_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(this, "Aun no ha creado un arbol",
                                        "Error!!", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese datos diferentes de 0",
                                    "Error!!", JOptionPane.WARNING_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese datos en el campo",
                                "Error!!", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El elemento ya habia sido ingresado previamente",
                            "Error!!", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese numeros enteros diferentes de 0",
                        "Error!!", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese datos en el campo",
                    "Error!!", JOptionPane.WARNING_MESSAGE);
        }
        jTextField1.setText("");

    }
    
    /*ActionPerformed del botón Eliminar, el cual elimina la clave dentro del árbol
    e informa si se encontraba o no.*/
    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        boolean esta = false;
        boolean numero = raizAux.esNumero(jTextField3.getText());
        if (!jTextField3.getText().equals("")) {
            if (numero) {
                if (ya) {
                    for (int i = 0; i < datos.ingresados.size(); i++) {
                        if (datos.ingresados.get(i) == Integer.parseInt(jTextField3.getText())) {
                            esta = true;
                        }
                    }
                    raiz1.eliminar(Integer.parseInt(jTextField3.getText()));
                    if (esta) {
                        JOptionPane.showMessageDialog(this, "El elemento " + jTextField3.getText()
                                + " fue eliminado exitosamente",
                                "Novedad", JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "El elemento " + jTextField3.getText()
                                + " no estaba en el arbol",
                                "Novedad", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Aun no ha creado un arbol",
                            "Error!!", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Ingrese numeros enteros diferentes de 0",
                        "Novedad", JOptionPane.WARNING_MESSAGE);

            }
            jTextField3.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese datos en el campo",
                    "Error!!", JOptionPane.WARNING_MESSAGE);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    private javax.swing.JFrame frameArbol;
    private javax.swing.JButton bInsetar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bVerArbol;
    private javax.swing.JButton bIniciarArbol;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;

}
